### ISSUE TITLE
No scale settings on monitor preferences

### ISSUE THREAD

**Issue by mudza09** [PRATAP-KUMAR/gdm-extension#1]
I really like the extension you made, thank you for this.

But may I ask, can you add a "scale" feature to each monitor setting. I use 125% scale for my monitor, but this seems to be ignored by gdm, I looked for the scale setting in your extension but I can't find it.

I hope you can fulfill my request, thank you

**Comment by PRATAP-KUMAR** [comment]
Hi, Can you give me a week time, I will get back to you after trying this by connecting to external TV and find a way for scaling.

Thanks

**Comment by mudza09** [comment]
also can u add feature to change fonts in your extensions, it would be really cool if we could have that feature!

**Comment by PRATAP-KUMAR** [comment]
Hi,
I will try to make it configurable via CSS. I will get back to you in couple of days @mudza09

**Comment by PRATAP-KUMAR** [comment]
HI @mudza09 I made it for Interface text for fonts, It is working but there is a risk if we don't provide the font name exactly. I was struck many times while testing it. It is better to set the font when you are on desktop and get the value from dconf. And use the same text with the gdm extension.

For example, first you choose your font from gnome-tweaks on desktop. Then go to dconf-editor/command line and get the value.

Pick a font says - "Lato Black"
![Screenshot from 2024-06-15 08-51-51](https://github.com/PRATAP-KUMAR/gdm-extension/assets/40719899/2a20308c-bdc2-4d9b-ae64-c0bbe4548cba)

After selection, it is showing "Lato Heavy"
![Screenshot from 2024-06-15 08-52-07](https://github.com/PRATAP-KUMAR/gdm-extension/assets/40719899/129056fb-2736-4cad-973e-5636f6cefd4c)

d-conf value is - "Lato Heavy 12"
![image](https://github.com/PRATAP-KUMAR/gdm-extension/assets/40719899/ecce2491-97d7-453c-8ab7-1be422a9ae99)

Lato Heavy 12 is the final string we need to input in gdm-extensions. If this is different from d-conf value we get, then we will be locked at gdm-screen, we cant enter any input. We need to reset the key from tty and then only we can access gdm-screen.

**Comment by PRATAP-KUMAR** [comment]
Regarding scale for individual monitor, I need much more time as I don't have any idea how to implement it.
With out this extension, are you able to use different scales on each monitor? whats the setup for it.
If you can provide me this, I will get some idea to start implementing it on gdm-extension.

Thanks

**Comment by PRATAP-KUMAR** [comment]
For setting the Font for Interface text from gdm-extension,
Add this line in your `gdmExtension.js` file, around after line number 96.

 ```
subMenuItem.menu.box.add_child(CreateActor(INTERFACE_SCHEMA, 'Interface Font Family', 'Cantarell 11', 'font-name', 'Font Name'));
```

after adding above line, the code should look like below around line numbers 94 to 100
```            
subMenuItem.menu.box.add_child(CreateActor(LOGIN_SCREEN_SCHEMA, 'Banner Message Text', 'Banner Message', 'banner-message-text'));
            subMenuItem.menu.box.add_child(CreateActor(LOGIN_SCREEN_SCHEMA, 'Logo', '/usr/share/pixmaps/logo.svg', 'logo'));
            subMenuItem.menu.box.add_child(CreateActor(INTERFACE_SCHEMA, 'clock format', '12h or 24h', 'clock-format', 'must be one of [12h, 24h]'));
            subMenuItem.menu.box.add_child(CreateActor(INTERFACE_SCHEMA, 'Interface Font Family', 'Cantarell 11', 'font-name', 'Font Name'));

            this.menu.addMenuItem(subMenuItem);
        }
```

**Comment by mudza09** [comment]
Hi Pratap,

Thank you very much for your hard work, I really appreciate this.

Regarding fonts, it would be better if we made it like a "shell themes" menu, so the fonts menu will display all the fonts available on the system and the user just has to choose the font he wants, just like we choose a shell theme.

For monitor scale, currently I am using dual monitors using a laptop and an external monitor, I use fractional scale settings of 125% on the laptop and 100% on the external monitor.

**Comment by PRATAP-KUMAR** [comment]
Hi @mudza09

Regarding fonts, as I indicated in the above, that is getting the font names same as shell-themes or icon-themes is not possible for me as it is complicated. As an example the custom font I installed is "Lato", when I try to set it from gnome-tweaks, the name shows is different, in dconf the name is different. I would like to skip this feature for now.

Regarding scaling, I just setup a sony tv infront of my laptop and trying to see whether I can achieve your requirement. Will get back to you in couple of hours.

Thanks.

**Comment by PRATAP-KUMAR** [comment]
Hi @mudza09, I took several hours on this issue after connecting my laptop with the sony TV.

The best way to replicate the scaling on GDM is the old way. i.e copy pasting the `.config/monitors.xml` file to gdm's `.config` folder.

I did achieve different scaling same as desktop and GDM on these two monitors(laptop and sony TV) without any difficulty just by following the old way as mentioned above. After several trail and errors I found that this is the best way.

You can use different scaling on desktop and GDM if you wish too, but that still needs to play with the old way.

Use this link to configure your setup https://gitlab.gnome.org/GNOME/gdm/-/issues/699

**Comment by PRATAP-KUMAR** [comment]
@mudza09

I found a way for Fonts.
I am not sure about time line, but will implement it in the future.

Thanks.

**Comment by PRATAP-KUMAR** [comment]
Hi @mudza09 
I have added the Fonts feature now.

Please note that Fonts are filtered by `FontFamilyName` based on font file naming convention and `StyleName` is ignored by this extension. And this extension grabs all `.otf` and `.ttf` fonts from `['/usr/local/share/fonts', '/usrshare/fonts']`

Thanks

**Comment by PRATAP-KUMAR** [comment]
https://github.com/PRATAP-KUMAR/gdm-extension/issues/1#issuecomment-2180231665
