### ISSUE TITLE
extension menu missing on Ubuntu 24.10

### ISSUE THREAD

**Issue by avision-it** [PRATAP-KUMAR/gdm-extension#4]
I recently upgraded from Ubuntu 24.04 to 24.10 and the menu on the gdm login screen disappeared. I tried to reinstall the extension but it didn't help.
It also doesn't work on a fresh install of Ubuntu 24.10. Is there a way to debug the extension or see some log messages?
There were no errors on make install (and uninstall).
And thanks for the great extension ;-) I love it!

**Comment by PRATAP-KUMAR** [comment]
Hi @avision-it
I didn’t install Ubuntu 24.10 yet.
Ubuntu always comes with its own customisations with its new release.

With GNOME 47 it’s working fine with my Arch Linux.
It will take some time for me to install and see for Ubuntu 24.10.

I will get back to you once I install 24.10

Thanks.

**Comment by PRATAP-KUMAR** [comment]
Hi @avision-it and @jmit79 since last 5 hours I have upgraded my Ubuntu 24.04 to 24.10 and found the issue.
Can you git pull and then run make and see?
```
git pull
```
and then
```
sudo make install
```

**Comment by avision-it** [comment]
Hey @PRATAP-KUMAR, thanks for your quick help. The fix is obvious ;-)

**Comment by PRATAP-KUMAR** [comment]
Hi I have gone through your website and applied for Full Stack Dev role. Please look into it.

Thanks.
