### ISSUE TITLE
not set background in debian trixie

### ISSUE THREAD

**Issue by netwarebsd** [PRATAP-KUMAR/gdm-extension#5]
Hello, I installed the extensions and performed all the recommended actions, I can make any settings except for choosing a picture for the background. Initially, there is no "backgrounds" folder in Debian, but I created it and the extensions began to see the files placed there, but selecting them does not lead to anything.
Please help

**Comment by PRATAP-KUMAR** [comment]
Hi
Where did you create it, the backgrounds folder.
If it is showing in the menu selecting it should work. Can you select gradient direction to horizontal or vertical and then set it to none. Can you post screenshots of gdm-extension when open.

I am waiting.

**Comment by netwarebsd** [comment]
> I am waiting.
path /usr/share/backgrounds
I attached the pictures sequentially: opening the settings, selecting the image, hiding the settings - in my case the picture is not displayed =(

![image](https://github.com/user-attachments/assets/ed38fae5-5898-4c2c-bbe8-b373e49899ce)
![1_gBaFJx1ik](https://github.com/user-attachments/assets/cbb9a885-f3fa-4ffa-803c-5416d859afd0)
![MsXxqFZi_0c](https://github.com/user-attachments/assets/5bdb0e84-1ffc-4022-aee2-e8fd93330565)

**Comment by PRATAP-KUMAR** [comment]
Ok can you rename the background picture to something without spaces like `my_background.png` and see??

Can you share link to your particular debian iso image?
If above doesn't work then I will see it in live.

Thanks.

**Comment by netwarebsd** [comment]
Thank you very much, it worked

**Comment by PRATAP-KUMAR** [comment]
Hi I have gnone trhough debian trixie. It is in testing stage.

I did see in my arch linux with spaces for background image file name and it is working.
I too does not have `/usr/share/backgrounds` folder initiallay. I created it and pasted images with spaces there and still working.

May I know what was your background image file name exactly? I am curious to know why it failed in the first attempt for you.

Thanks.

**Comment by netwarebsd** [comment]
"STONERCCUBUS1.png" was previously "STONERCCUBUS 1.png" (author: merunyaa) - after renaming, if you simply select the image, nothing changed. It worked after I first set a new gradient, and moved the transparency/darkening sliders, and if you select the image after that, it will be displayed.

**Comment by PRATAP-KUMAR** [comment]
Ok it seems file name is not the cause here.
And I guess "testing" stage of the OS may be the cause.

Thanks @netwarebsd

**Comment by PRATAP-KUMAR** [comment]
Hi @netwarebsd 

Out of curiosity, I have downloaded debian 12, installed and tested this gdm-extension.
I understood that Debian is having those wallpapers in `/usr/share/gnome/backgrounds` with `.webp` ext.

So I have refactored the code to look for this directory for backgrounds. This means when the extension is installed,
the gdm-extension menu will show the backgrounds present in this directory so that user dont need to create a folder, move/copy the image and test.

you may test the extension now.
```
git pull
sudo ./install.sh
```

Thank You
